# include:
#   - template: Auto-DevOps.gitlab-ci.yml

# variables:
#   #### CONFIG ####
#   DEBUG: '1'
#   KEYCLOAK_BASE_URL: https://example.com?keycloak
#   KEYCLOAK_CLEANUP: 'true'
#   KEYCLOAK_CLIENT_ID: 'g-${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}'
#   KEYCLOAK_CLIENT_SECRET_ENABLED: 'false'
#   KEYCLOAK_REALM: main

#   #### ENVS ####
#   K8S_SECRET_DEBUG: '${DEBUG}'
#   K8S_SECRET_KEYCLOAK_BASE_URL: '${KEYCLOAK_BASE_URL}'
#   K8S_SECRET_KEYCLOAK_CLIENT_ID: '${KEYCLOAK_CLIENT_ID}'
#   K8S_SECRET_KEYCLOAK_REALM: '${KEYCLOAK_REALM}'

#   #### JOBS ####
#   TEST_DISABLED: '1'
#   BUILD_DISABLED: ''
#   CODE_QUALITY_DISABLED: '1'
#   LICENSE_MANAGEMENT_DISABLED: '1'
#   BROWSER_PERFORMANCE_DISABLED: '1'
#   LOAD_PERFORMANCE_DISABLED: '1'
#   SAST_DISABLED: '1'
#   SECRET_DETECTION_DISABLED: '1'
#   DEPENDENCY_SCANNING_DISABLED: '1'
#   CONTAINER_SCANNING_DISABLED: '1'
#   DAST_DISABLED: '1'
#   REVIEW_DISABLED: ''
#   CODE_INTELLIGENCE_DISABLED: '1'

#   #### AUTO DEVOPS ####
#   # BUILDPACK_URL=
#   DOCKERFILE_PATH: docker/Dockerfile
#   STAGING_ENABLED: '1'
#   INCREMENTAL_ROLLOUT_MODE: manual
#   CANARY_ENABLED: ''
#   POSTGRES_ENABLED: 'false'
#   AUTO_DEVOPS_CHART_REPOSITORY: https://risserlabs.gitlab.io/community/charts
#   AUTO_DEVOPS_CHART_REPOSITORY_NAME: risserlabs
#   AUTO_DEVOPS_CHART: risserlabs/auto-deploy-app
#   KUBE_NAMESPACE: 'g-${CI_PROJECT_NAME}-${CI_PROJECT_ID}'
#   HELM_UPGRADE_EXTRA_ARGS: >
#     --version=2.35.0
#     --set integrations.keycloak.cleanup=${KEYCLOAK_CLEANUP}
#     --set integrations.keycloak.clientId=${KEYCLOAK_CLIENT_ID}
#     --set integrations.keycloak.clientSecret=${KEYCLOAK_CLIENT_SECRET}
#     --set integrations.keycloak.clientSecretEnabled=${KEYCLOAK_CLIENT_SECRET_ENABLED}
#     --set integrations.keycloak.name=${KEYCLOAK_INTEGRATION}

variables:
  BUILDKIT_INLINE_CACHE: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CERT_PATH: $DOCKER_TLS_CERTDIR/client
  DOCKER_TLS_VERIFY: 1

stages:
  - build

docker-build:
  image: registry.gitlab.com/bitspur/rock8s/images/docker:25.0.5
  stage: build
  services:
    - name: docker:25.0.5-dind
      command: ["--experimental"]
  before_script:
    - |
      if [ ! -f "$DOCKER_CERT_PATH/ca.pem" ]; then
        export DOCKER_TLS_VERIFY=0
        export DOCKER_HOST=tcp://docker:2375
      fi
    - docker context create builder-context --docker host=$DOCKER_HOST
    - |
      if [ ! -f "$DOCKER_CERT_PATH/ca.pem" ]; then
        docker buildx create builder-context --use --config /etc/docker/buildkitd.toml
      else
        docker buildx create builder-context --use
      fi
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - (echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin docker.io) || true
  script:
    - ./mkpm docker/bake
  when: manual
# pages:
#   stage: deploy
#   image: registry.gitlab.com/risserlabs/community/images/loki:0.0.1
#   script:
#     - rm -rf public
#     ## public storybook ##
#     - make -s build
#     - make -s storybook/build
#     - cp -r platforms/storybook/storybook-static public
#     ## public next ##
#     # - make -s next/export
#     # - cp -r platforms/next/out public
#   artifacts:
#     paths:
#       - public
#   only:
#     - main
#   when: manual
