schema: packages/gql/generated/schema.graphql
documents:
  - api/**/*.{ts,tsx,graphql,gql}
  - app/**/*.{ts,tsx,graphql,gql}
  - '!api/node_modules/**/*.{ts,tsx,graphql,gql}'
  - '!app/node_modules/**/*.{ts,tsx,graphql,gql}'
extensions:
  endpoints:
    default:
      url: http://api.localhost/graphql
