services:
  devcontainer:
    image: registry.gitlab.com/bitspur/multiplatform.one/multiplatform.one/devcontainer:latest
    command: sleep infinity
    network_mode: host
    privileged: true
    working_dir: /workspace/development
    extra_hosts:
      account.localhost: 127.0.0.1
      account.test: 127.0.0.1
      app.localhost: 127.0.0.1
      app.test: 127.0.0.1
      docs.localhost: 127.0.0.1
      docs.test: 127.0.0.1
      frappe.localhost: 127.0.0.1
      frappe.test: 127.0.0.1
      storybook.localhost: 127.0.0.1
      storybook.test: 127.0.0.1
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
      - SYS_CHROOT
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
      - DISPLAY
      - GNOME_SHELL_THEME=dark
      - GTK_APPLICATION_PREFER_DARK_THEME=1
      - GTK_THEME=Adwaita:dark
      - LIBGL_ALWAYS_SOFTWARE=1
      - MESA_GLSL_VERSION_OVERRIDE=450
      - MESA_GL_VERSION_OVERRIDE=4.5
      - XAUTHORITY=/tmp/.docker.xauth
    devices:
      - /dev/dri:/dev/dri
    tmpfs:
      - /dev/shm:rw,nosuid,nodev,exec,size=2g
      - /tmp:rw,nosuid,nodev,exec,size=2g,mode=1777
    volumes:
      - ${XAUTHORITY:-~/.Xauthority}:/tmp/.docker.xauth:rw
      - ..:/workspace/development:rw
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock

  caddy:
    image: caddy:latest
    restart: unless-stopped
    network_mode: host
    env_file:
      - ../.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config

  dns:
    restart: unless-stopped
    image: registry.gitlab.com/bitspur/multiplatform.one/multiplatform.one/dns:latest
    network_mode: host
    cap_add:
      - NET_ADMIN
    env_file:
      - ../.env

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  redis-cache:
    image: docker.io/redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  redis-queue:
    image: docker.io/redis:alpine
    restart: unless-stopped
    ports:
      - 6380:6379

  keycloak:
    container_name: keycloak
    restart: unless-stopped
    image: registry.gitlab.com/bitspur/rock8s/images/keycloak:25.0.1
    ports:
      - 8080:8080
    volumes:
      - ../platforms/keycloak/docker/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command:
      - start
      - --import-realm
      - --optimized
    environment:
      KC_DB_URL_DATABASE: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_PASSWORD: postgres
      KC_DB_URL_USERNAME: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: P@ssw0rd
    depends_on:
      - postgres-keycloak

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  postgres-keycloak:
    container_name: postgres-keycloak
    restart: unless-stopped
    image: postgres:14.5
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-keycloak:/var/lib/postgresql/data

volumes:
  caddy-config: {}
  caddy-data: {}
  mailpit: {}
  postgres-keycloak: {}
  postgres: {}
