services:
  devcontainer:
    image: registry.gitlab.com/bitspur/frappe/images/devcontainer:latest
    command: sleep infinity
    working_dir: /workspace/development
    volumes:
      - ..:/workspace/development:rw
    ports:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005

  # mariadb:
  #   image: docker.io/mariadb:10.6
  #   command:
  #     - --character-set-server=utf8mb4
  #     - --collation-server=utf8mb4_unicode_ci
  #     - --skip-character-set-client-handshake
  #     - --skip-innodb-read-only-compressed
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: P@ssw0rd
  #   volumes:
  #     - mariadb:/var/lib/mysql

  postgres:
    image: docker.io/postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - postgres:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    volumes:
      - mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  redis-cache:
    image: docker.io/redis:alpine

  redis-queue:
    image: docker.io/redis:alpine

volumes:
  mailpit: {}
  # mariadb: {}
  postgres: {}
