sources:
  - name: Api
    handler:
      graphql:
        endpoint: http://localhost:5001/graphql
        operationHeaders:
          Authorization: "{context.headers.Authorization}"
          Cookie: "{context.headers.Cookie}"
    transforms:
      - prefix:
          mode: wrap
          value: Api_
      - filterSchema:
          mode: wrap
          filters: []
  - name: Frappe
    handler:
      graphql:
        endpoint: http://frappe.localhost/api/method/graphql
        operationHeaders:
          Authorization: "{context.headers.Authorization}"
          Cookie: "{context.headers.Cookie}"
    transforms:
      - filterSchema:
          mode: wrap
          filters: []
plugins:
  - rateLimit:
      config: []
  - maxTokens:
      n: 1000
  - maxDepth:
      n: 10
  - blockFieldSuggestions: {}
  - operationFieldPermissions:
      permissions:
        - if: 'true'
          allow:
            - '*'
  - responseCache: {}
