sources:
  - name: Api
    handler:
      graphql:
        endpoint: http://localhost:5001/graphql
        subscriptionsEndpoint: ws://localhost:5001/graphql
        subscriptionsProtocol: WS
        operationHeaders:
          Authorization: "{context.headers.Authorization}"
          Cookie: "{context.headers.Cookie}"
    transforms:
      - prefix:
          mode: wrap
          value: Api
      - filterSchema:
          mode: wrap
          filters: []
  - name: Frappe
    handler:
      graphql:
        endpoint: http://frappe.localhost/api/method/graphql
        subscriptionsEndpoint: ws://frappe.localhost/api/method/graphql
        subscriptionsProtocol: WS
        operationHeaders:
          Authorization: "{context.headers.Authorization}"
          Cookie: "{context.headers.Cookie}"
    transforms:
      - prefix:
          mode: wrap
          value: Frappe
      - filterSchema:
          mode: wrap
          filters:
            - "Subscription.doc_events"
serve:
  browser: false
additionalEnvelopPlugins: './plugins/envelopPlugins'
plugins:
  - rateLimit:
      config: []
  - maxTokens:
      n: 1000
  - maxDepth:
      n: 10
  - blockFieldSuggestions: {}
  - responseCache: {}
